### ISSUE TITLE
Font/Icon is not correctly loaded at Firefox

### ISSUE THREAD

**Issue by haoliangyu** [GeoNode/geonode.github.com#55] opened 2017-01-15 03:04 UTC
Firefox 47.0 at Ubuntu 16.04. It's working well at Chrome.

![screenshot from 2017-01-14 22-02-32](https://cloud.githubusercontent.com/assets/1726265/21959944/51d41c0a-daa5-11e6-89b3-bd91f0cb3039.png)

**Comment by devurandom** [comment] 2017-09-22 16:51
issue #49 is a duplicate of this

**Comment by t-book** [comment] 2019-07-08 10:58
Fixed with newer Firefox Version. As Firefox is an evergreen browser this should be fixed for users when their version gets updated. Closing.

**Closed by t-book** 2019-07-08 10:58 UTC
